// Code generated by go/internal/gen; DO NOT EDIT.

package guides

// SchemaVersion is the guide.v1 schema_version embedded at generation time.
const SchemaVersion = 1

var generatedSlugs = []GuideSlug{
	"asana",
	"atlassian",
	"box",
	"github",
	"google-big-query",
	"google-calendar",
	"google-compute-engine",
	"google-docs",
	"google-drive",
	"google-people",
	"google-sheets",
	"google-slides",
	"hubspot",
	"intercom",
	"netsuite",
	"salesforce",
	"snowflake",
	"x",
	"x-docs",
	"zapier",
}

type generatedRemote struct {
	ID        RemoteID
	URL       string
	Transport string
	Tenanted  bool
}

type generatedCredentialOption struct {
	ID                 string
	Kind               string
	ClientRegistration string
	UpstreamSetup      string
	SpeakeasySetup     string
}

type generatedGuide struct {
	Slug               GuideSlug
	Title              string
	Summary            string
	SpeakeasyAddServer string
	SetupRequired      bool
	Aliases            []string
	Remotes            []generatedRemote
	CredentialOptions  []generatedCredentialOption
}

var generatedGuides = map[GuideSlug]generatedGuide{
	"asana": {
		Slug:               "asana",
		Title:              "Asana",
		Summary:            "Connect an Asana workspace so users can access and manage their permitted Asana work through the hosted Asana MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/asana-mcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.asana.com/v2/mcp", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-mcp-app", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"atlassian": {
		Slug:               "atlassian",
		Title:              "Atlassian Rovo",
		Summary:            "Connect Atlassian Rovo so users can access their permitted Jira, Confluence, and Compass work through the hosted MCP server.",
		SpeakeasyAddServer: "auto",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "rovo", URL: "https://mcp.atlassian.com/v1/mcp/authv2", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-dcr", Kind: "oauth", ClientRegistration: "dynamic", UpstreamSetup: "provider-steps", SpeakeasySetup: "dcr"},
		},
	},
	"box": {
		Slug:               "box",
		Title:              "Box",
		Summary:            "Access, search, and manage Box content and Box AI through the hosted Box MCP server.",
		SpeakeasyAddServer: "catalog",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/box"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.box.com", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-integration", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"github": {
		Slug:               "github",
		Title:              "GitHub",
		Summary:            "Connect GitHub so users can work with repositories and other resources their GitHub account is permitted to access through GitHub's hosted MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{"io.github.github/github-mcp-server"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://api.githubcopilot.com/mcp/", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-app", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-big-query": {
		Slug:               "google-big-query",
		Title:              "Google BigQuery",
		Summary:            "Query and manage BigQuery data through Google's hosted BigQuery MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/google-bigquery"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://bigquery.googleapis.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-calendar": {
		Slug:               "google-calendar",
		Title:              "Google Calendar",
		Summary:            "Connect Google Calendar data through Google's hosted Calendar MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://calendarmcp.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-compute-engine": {
		Slug:               "google-compute-engine",
		Title:              "Google Compute Engine",
		Summary:            "Manage Compute Engine VM instances, disks, instance groups, snapshots, and images through Google's hosted Compute Engine MCP server.",
		SpeakeasyAddServer: "catalog",
		SetupRequired:      true,
		Aliases:            []string{"com.googleapis.compute/mcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://compute.googleapis.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-docs": {
		Slug:               "google-docs",
		Title:              "Google Docs",
		Summary:            "Read and update Google Docs through Google's hosted Docs MCP server.",
		SpeakeasyAddServer: "custom-remote",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://docsmcp.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-drive": {
		Slug:               "google-drive",
		Title:              "Google Drive",
		Summary:            "Connect Google's hosted Drive MCP server to read and create files under each user's existing Drive permissions.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://drivemcp.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-people": {
		Slug:               "google-people",
		Title:              "Google People",
		Summary:            "Connect Google profile, contacts, and directory data through Google's hosted People API MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://people.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-sheets": {
		Slug:               "google-sheets",
		Title:              "Google Sheets",
		Summary:            "Connect Google Sheets data through Google's hosted Sheets MCP server.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://sheetsmcp.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"google-slides": {
		Slug:               "google-slides",
		Title:              "Google Slides",
		Summary:            "Connect Google Slides data through Google's hosted Slides MCP server.",
		SpeakeasyAddServer: "custom-remote",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://slidesmcp.googleapis.com/mcp/v1", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"hubspot": {
		Slug:               "hubspot",
		Title:              "HubSpot",
		Summary:            "Connect HubSpot's hosted MCP server using an MCP auth app and OAuth.",
		SpeakeasyAddServer: "catalog",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/hubspot"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.hubspot.com", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-mcp-auth-app", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"intercom": {
		Slug:               "intercom",
		Title:              "Intercom",
		Summary:            "Connect a US- or EU-hosted Intercom workspace through Intercom's hosted MCP server using a manually registered OAuth app.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/intercom"},
		Remotes: []generatedRemote{
			{ID: "us", URL: "https://mcp.intercom.com/mcp", Transport: "streamable-http", Tenanted: true},
			{ID: "eu", URL: "https://mcp.eu.intercom.com/mcp", Transport: "streamable-http", Tenanted: true},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-manual", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"netsuite": {
		Slug:               "netsuite",
		Title:              "NetSuite",
		Summary:            "Connect the account-specific NetSuite AI Connector Service with MCP Standard Tools and a scoped public OAuth client.",
		SpeakeasyAddServer: "custom-remote",
		SetupRequired:      true,
		Aliases:            []string{},
		Remotes: []generatedRemote{
			{ID: "mcp-standard-tools", URL: "https://<accountid>.suitetalk.api.netsuite.com/services/mcp/v1/suiteapp/com.netsuite.mcpstandardtools", Transport: "streamable-http", Tenanted: true},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-public-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"salesforce": {
		Slug:               "salesforce",
		Title:              "Salesforce",
		Summary:            "Connect to Salesforce records through hosted SObject MCP servers with selectable read, write, and delete boundaries.",
		SpeakeasyAddServer: "custom-remote",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/gram-salesforce"},
		Remotes: []generatedRemote{
			{ID: "sobject-reads-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-reads", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-reads-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-reads", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-mutations-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-mutations", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-mutations-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-mutations", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-deletes-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-deletes", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-deletes-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-deletes", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-all-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-all", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-all-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-all", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"snowflake": {
		Slug:               "snowflake",
		Title:              "Snowflake",
		Summary:            "Connect the Speakeasy AI Control Plane to a Snowflake-managed MCP server that exposes an existing Cortex Agent.",
		SpeakeasyAddServer: "custom-remote",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/gram-snowflake"},
		Remotes: []generatedRemote{
			{ID: "cortex-agent-mcp", URL: "https://<account_url>/api/v2/databases/<mcp_database>/schemas/<mcp_schema>/mcp-servers/<mcp_server_name>", Transport: "streamable-http", Tenanted: true},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-client", Kind: "oauth", ClientRegistration: "manual", UpstreamSetup: "provider-steps", SpeakeasySetup: "manual-oauth"},
		},
	},
	"x": {
		Slug:               "x",
		Title:              "X",
		Summary:            "Connect the hosted X MCP server for read-only public-data access using an app-only Bearer Token.",
		SpeakeasyAddServer: "",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/xdevplatform-xmcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://api.x.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "app-only-bearer", Kind: "api_key", ClientRegistration: "", UpstreamSetup: "provider-steps", SpeakeasySetup: "headers"},
		},
	},
	"x-docs": {
		Slug:               "x-docs",
		Title:              "X Docs",
		Summary:            "Connect X's public documentation MCP server for searching and reading X API documentation.",
		SpeakeasyAddServer: "catalog",
		SetupRequired:      false,
		Aliases:            []string{"com.pulsemcp.mirror/x-docs"},
		Remotes: []generatedRemote{
			{ID: "docs", URL: "https://docs.x.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "public", Kind: "open", ClientRegistration: "", UpstreamSetup: "none", SpeakeasySetup: "none"},
		},
	},
	"zapier": {
		Slug:               "zapier",
		Title:              "Zapier",
		Summary:            "Connect Zapier so agents can discover and run actions in your connected apps.",
		SpeakeasyAddServer: "catalog",
		SetupRequired:      true,
		Aliases:            []string{"com.pulsemcp.mirror/zapier"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.zapier.com/api/v1/connect", Transport: "streamable-http", Tenanted: false},
		},
		CredentialOptions: []generatedCredentialOption{
			{ID: "oauth-dcr", Kind: "oauth", ClientRegistration: "dynamic", UpstreamSetup: "none", SpeakeasySetup: "dcr"},
		},
	},
}

var generatedAliasToSlug = map[string]GuideSlug{
	"com.googleapis.compute/mcp":            "google-compute-engine",
	"com.pulsemcp.mirror/asana-mcp":         "asana",
	"com.pulsemcp.mirror/box":               "box",
	"com.pulsemcp.mirror/google-bigquery":   "google-big-query",
	"com.pulsemcp.mirror/gram-salesforce":   "salesforce",
	"com.pulsemcp.mirror/gram-snowflake":    "snowflake",
	"com.pulsemcp.mirror/hubspot":           "hubspot",
	"com.pulsemcp.mirror/intercom":          "intercom",
	"com.pulsemcp.mirror/x-docs":            "x-docs",
	"com.pulsemcp.mirror/xdevplatform-xmcp": "x",
	"com.pulsemcp.mirror/zapier":            "zapier",
	"io.github.github/github-mcp-server":    "github",
}

var generatedURLToRefs = map[string][]ServerRef{
	"https://api.githubcopilot.com/mcp": {
		{Guide: "github", Remote: "hosted"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-all": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-deletes": {
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-mutations": {
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-reads": {
		{Guide: "salesforce", Remote: "sobject-reads-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-all": {
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-deletes": {
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-mutations": {
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-reads": {
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"https://api.x.com/mcp": {
		{Guide: "x", Remote: "hosted"},
	},
	"https://bigquery.googleapis.com/mcp": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"https://calendarmcp.googleapis.com/mcp/v1": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"https://compute.googleapis.com/mcp": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"https://docs.x.com/mcp": {
		{Guide: "x-docs", Remote: "docs"},
	},
	"https://docsmcp.googleapis.com/mcp/v1": {
		{Guide: "google-docs", Remote: "hosted"},
	},
	"https://drivemcp.googleapis.com/mcp/v1": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"https://mcp.asana.com/v2/mcp": {
		{Guide: "asana", Remote: "hosted"},
	},
	"https://mcp.atlassian.com/v1/mcp/authv2": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"https://mcp.box.com": {
		{Guide: "box", Remote: "hosted"},
	},
	"https://mcp.eu.intercom.com/mcp": {
		{Guide: "intercom", Remote: "eu"},
	},
	"https://mcp.hubspot.com": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"https://mcp.intercom.com/mcp": {
		{Guide: "intercom", Remote: "us"},
	},
	"https://mcp.zapier.com/api/v1/connect": {
		{Guide: "zapier", Remote: "hosted"},
	},
	"https://people.googleapis.com/mcp/v1": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"https://sheetsmcp.googleapis.com/mcp/v1": {
		{Guide: "google-sheets", Remote: "hosted"},
	},
	"https://slidesmcp.googleapis.com/mcp/v1": {
		{Guide: "google-slides", Remote: "hosted"},
	},
}

var generatedProvenanceToRefs = map[string][]ServerRef{
	"API": {
		{Guide: "asana", Remote: "hosted"},
	},
	"About Box MCP Server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Account identifiers": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Activate MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Adding Integration Credentials for Customer-Instance Integrations": {
		{Guide: "box", Remote: "hosted"},
	},
	"Anthropic Messages API": {
		{Guide: "box", Remote: "hosted"},
	},
	"App management and integrations": {
		{Guide: "asana", Remote: "hosted"},
	},
	"App only authentication and OAuth 2.0 Bearer Token": {
		{Guide: "x", Remote: "hosted"},
	},
	"Approving OAuth apps for your organization": {
		{Guide: "github", Remote: "hosted"},
	},
	"Apps": {
		{Guide: "x", Remote: "hosted"},
	},
	"Asana": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Atlassian Rovo MCP server": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Atlassian authorization-server metadata with DCR registration endpoint": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Atlassian base authorization-server metadata": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Authenticate to Google and Google Cloud MCP servers": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Authenticating to the REST API": {
		{Guide: "github", Remote: "hosted"},
	},
	"Authentication": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
		{Guide: "x", Remote: "hosted"},
	},
	"Authentication and authorization": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Authorizing OAuth apps": {
		{Guide: "github", Remote: "hosted"},
	},
	"Available Atlassian Rovo MCP server domains": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Available Tools": {
		{Guide: "box", Remote: "hosted"},
	},
	"BigQuery IAM roles and permissions": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP endpoint": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP endpoint (tools/list 200 unauthenticated; tools/call 401)": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP protected-resource metadata": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP reference": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Box MCP resource documentation": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box MCP server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box Model Context Protocol Server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box docs index": {
		{Guide: "box", Remote: "hosted"},
	},
	"CREATE MCP SERVER": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"CREATE ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"CREATE SECURITY INTEGRATION (Snowflake OAuth)": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Choose Google Calendar API scopes": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"Choose Google Docs API scopes": {
		{Guide: "google-docs", Remote: "hosted"},
	},
	"Choose Google Drive API scopes": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Choose Google Slides API scopes": {
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Claude Code": {
		{Guide: "box", Remote: "hosted"},
	},
	"Compute Engine IAM roles and permissions": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP endpoint (tools/list 200 unauthenticated, tools/call 401)": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP protected-resource metadata": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP reference": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Configure Cursor": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Configure Postman": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Configure Snowflake OAuth for custom clients": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Configure a third-party application to connect to Snowflake": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Configure an email channel for OAuth with Gmail": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Configure security for Google Workspace MCP servers": {
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Configure the Calendar MCP server": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"Configure the Docs MCP server": {
		{Guide: "google-docs", Remote: "hosted"},
	},
	"Configure the Drive MCP server": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Configure the Google Workspace MCP servers": {
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Configure the OAuth consent screen and choose scopes": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Configure the People API MCP server": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"Configure the Sheets MCP server": {
		{Guide: "google-sheets", Remote: "hosted"},
	},
	"Configure the Slides MCP server": {
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Configuring Box AI": {
		{Guide: "box", Remote: "hosted"},
	},
	"Configuring OAuth 2.1": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Configuring authentication via API token": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Configuring the GitHub MCP Server for GitHub Enterprise": {
		{Guide: "github", Remote: "hosted"},
	},
	"Connect Claude with Salesforce Hosted MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Connect to the NetSuite AI Connector Service": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Connecting Coding Clients to Asana's V2 server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Connecting an MCP Client": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Control Atlassian Rovo MCP server settings": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Control which apps access Google Workspace data": {
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Cortex Agents access control and authentication": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Create Integration Records for Applications to Use OAuth 2.0": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Create access credentials": {
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
	},
	"Create an External Client App": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Create and manage Cortex Agents": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Create future reservation requests": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Create projects": {
		{Guide: "google-sheets", Remote: "hosted"},
	},
	"Creating an OAuth app": {
		{Guide: "github", Remote: "hosted"},
	},
	"Developer Console": {
		{Guide: "x", Remote: "hosted"},
	},
	"Developer updates for June 2026": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Drive MCP file eligibility": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Enable Google Workspace APIs": {
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
	},
	"Enable and disable services": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Enterprise Settings: Content & Sharing Tab": {
		{Guide: "box", Remote: "hosted"},
	},
	"GRANT DATABASE ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"GRANT ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"GRANT privileges to role": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Get Started with the NetSuite AI Connector Service": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Get started with the Google Auth Platform": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Getting Access": {
		{Guide: "x", Remote: "hosted"},
	},
	"Getting Started with Managed Snowflake MCP Server": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Getting started with the Atlassian Rovo MCP Server": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"GitHub MCP Registry": {
		{Guide: "box", Remote: "hosted"},
	},
	"GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"GitHub MCP Server Installation Guides": {
		{Guide: "github", Remote: "hosted"},
	},
	"GitHub Remote MCP Integration Guide for MCP Host Authors": {
		{Guide: "github", Remote: "hosted"},
	},
	"Giving an Employee Access to NetSuite": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Google Calendar MCP endpoint": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"Google Calendar MCP protected-resource metadata": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"Google Cloud MCP quotas and system limits": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Google Cloud MCP servers overview": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Google Cloud MCP servers release notes": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Google Compute Engine": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Google Docs MCP endpoint": {
		{Guide: "google-docs", Remote: "hosted"},
	},
	"Google Docs MCP protected-resource metadata": {
		{Guide: "google-docs", Remote: "hosted"},
	},
	"Google Drive MCP endpoint": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Google Drive MCP protected-resource metadata": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Google Drive MCP reference": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Google People API MCP endpoint": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"Google People API MCP protected-resource metadata": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"Google Sheets MCP endpoint": {
		{Guide: "google-sheets", Remote: "hosted"},
	},
	"Google Sheets MCP protected-resource metadata": {
		{Guide: "google-sheets", Remote: "hosted"},
	},
	"Google Slides MCP endpoint": {
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Google Slides MCP protected-resource metadata": {
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Google Workspace developer release notes": {
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Google and Google Cloud products with MCP support": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"Google authorization-server metadata": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Grant an IAM role by using the Google Cloud console": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"HubSpot MCP Server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"HubSpot developer documentation index": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"HubSpot user permissions guide": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Installing the MCP Standard Tools SuiteApp": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Integrate AI tools with the HubSpot MCP server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Integrating with Asana's MCP Server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Intercom developer documentation index": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Intercom sign-in page": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Log In to Your Org": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"MCP Frequently Asked Questions": {
		{Guide: "box", Remote: "hosted"},
	},
	"MCP Server Activity Report": {
		{Guide: "box", Remote: "hosted"},
	},
	"MCP Standard Tools SuiteApp": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"MCP servers for the X API and X developer docs": {
		{Guide: "x-docs", Remote: "docs"},
		{Guide: "x", Remote: "hosted"},
	},
	"Make your first Google Health API call": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Manage App Audience": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Manage App Data Access": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Manage MCP servers": {
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Manage OAuth App Branding": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Manage OAuth Clients": {
		{Guide: "google-calendar", Remote: "hosted"},
	},
	"Manage Tool Access": {
		{Guide: "box", Remote: "hosted"},
	},
	"Manage your app": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Managing Box MCP Servers": {
		{Guide: "box", Remote: "hosted"},
	},
	"Model Context Protocol (MCP)": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"NetSuite AI Connector Service FAQ": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"No exact current Atlassian Rovo title/name match": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"OAuth": {
		{Guide: "asana", Remote: "hosted"},
	},
	"OAuth 2.0 Authorization Code Flow with PKCE": {
		{Guide: "x", Remote: "hosted"},
	},
	"OAuth 2.0 Scopes for Google APIs": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"OAuth Scopes": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"People API MCP reference": {
		{Guide: "google-people", Remote: "hosted"},
	},
	"Policies & Governance for the GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Prerequisite 1 - Create and Configure an External Client App": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Pricing": {
		{Guide: "box", Remote: "hosted"},
	},
	"Products Supporting MCP": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Public Beta: Self-Service MCP Auth Apps for the HubSpot Remote MCP Server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Querying semi-structured data": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Quotas and system limits": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Regional Data Hosting": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Remote GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Remote HubSpot MCP server is now generally available": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Requesting organization approval for OAuth apps": {
		{Guide: "github", Remote: "hosted"},
	},
	"Required Features and Permissions": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Revoke access to a Google Cloud project": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"SObject All": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Deletes": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Mutations": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Reads": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SYSTEM$SHOW_OAUTH_CLIENT_SECRETS": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Salesforce Hosted MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce Hosted MCP Servers Are Now Generally Available": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce SObject Reads production endpoint": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce SObject Reads protected-resource metadata": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Scope Filtering": {
		{Guide: "github", Remote: "hosted"},
	},
	"Sensitive scope verification": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Server Connection Failures": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Set up a Workspace": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Set up authentication for Google and Google Cloud MCP servers": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Set up authentication to Google and Google Cloud MCP servers": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
	},
	"Setting up OAuth": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Setting up clients": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Setting up the GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Share your app": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Snowflake Cortex documentation index": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake Documentation index": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake OAuth overview": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake-managed MCP server": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Speakeasy callback and catalog-path observations": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Speakeasy identity-provider attachment sheet": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Speakeasy identity-provider form fields": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Speakeasy setup canonical file": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Speakeasy setup canonical section": {
		{Guide: "asana", Remote: "hosted"},
		{Guide: "atlassian", Remote: "rovo"},
		{Guide: "github", Remote: "hosted"},
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-calendar", Remote: "hosted"},
		{Guide: "google-docs", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
		{Guide: "google-people", Remote: "hosted"},
		{Guide: "google-sheets", Remote: "hosted"},
		{Guide: "google-slides", Remote: "hosted"},
		{Guide: "hubspot", Remote: "hosted"},
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
		{Guide: "x-docs", Remote: "docs"},
		{Guide: "x", Remote: "hosted"},
	},
	"Specify IP addresses for product access": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Spring 2026 Spotlight": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Standard MCP Servers Reference": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Submitting your app for verification": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Supported AI Platforms": {
		{Guide: "box", Remote: "hosted"},
	},
	"Supported products": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Troubleshooting and verifying your setup": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"Try BigQuery using the sandbox": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"URLs for Account-Specific Domains": {
		{Guide: "netsuite", Remote: "mcp-standard-tools"},
	},
	"Understanding AI Units In Box": {
		{Guide: "box", Remote: "hosted"},
	},
	"Understanding Requests to Authorize or Allow Applications": {
		{Guide: "box", Remote: "hosted"},
	},
	"Update Salesforce Settings for Tableau Next Embedding": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Use the BigQuery MCP server": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Use the Compute Engine MCP server": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Using Asana's MCP Server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Using OAuth 2.0 to Access Google APIs": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
		{Guide: "google-drive", Remote: "hosted"},
	},
	"Using with other supported MCP clients": {
		{Guide: "atlassian", Remote: "rovo"},
	},
	"V2 MCP server now generally available": {
		{Guide: "asana", Remote: "hosted"},
	},
	"What is the admin console?": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Working with workspaces": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Workspaces": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"X API pay-per-usage pricing and credits": {
		{Guide: "x", Remote: "hosted"},
	},
	"X Developer Platform documentation index": {
		{Guide: "x-docs", Remote: "docs"},
		{Guide: "x", Remote: "hosted"},
	},
	"X Docs": {
		{Guide: "x-docs", Remote: "docs"},
	},
	"X Docs MCP": {
		{Guide: "x-docs", Remote: "docs"},
	},
	"com.pulsemcp.mirror/box": {
		{Guide: "box", Remote: "hosted"},
	},
	"com.pulsemcp.mirror/hubspot": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"com.pulsemcp.mirror/zapier": {
		{Guide: "zapier", Remote: "hosted"},
	},
	"xurl": {
		{Guide: "x", Remote: "hosted"},
	},
}
