// Code generated by go/internal/gen; DO NOT EDIT.

package guides

// SchemaVersion is the guide.v1 schema_version embedded at generation time.
const SchemaVersion = 1

var generatedSlugs = []GuideSlug{
	"asana",
	"box",
	"github",
	"google-big-query",
	"google-compute-engine",
	"hubspot",
	"intercom",
	"salesforce",
	"snowflake",
	"x",
	"zapier",
}

type generatedRemote struct {
	ID        RemoteID
	URL       string
	Transport string
	Tenanted  bool
}

type generatedGuide struct {
	Slug    GuideSlug
	Title   string
	Aliases []string
	Remotes []generatedRemote
}

var generatedGuides = map[GuideSlug]generatedGuide{
	"asana": {
		Slug:    "asana",
		Title:   "Asana",
		Aliases: []string{"com.pulsemcp.mirror/asana-mcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.asana.com/v2/mcp", Transport: "streamable-http", Tenanted: false},
		},
	},
	"box": {
		Slug:    "box",
		Title:   "Box",
		Aliases: []string{"com.pulsemcp.mirror/box"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.box.com", Transport: "streamable-http", Tenanted: false},
		},
	},
	"github": {
		Slug:    "github",
		Title:   "GitHub",
		Aliases: []string{"io.github.github/github-mcp-server"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://api.githubcopilot.com/mcp/", Transport: "streamable-http", Tenanted: false},
		},
	},
	"google-big-query": {
		Slug:    "google-big-query",
		Title:   "Google BigQuery",
		Aliases: []string{"com.pulsemcp.mirror/google-bigquery"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://bigquery.googleapis.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
	},
	"google-compute-engine": {
		Slug:    "google-compute-engine",
		Title:   "Google Compute Engine",
		Aliases: []string{"com.googleapis.compute/mcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://compute.googleapis.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
	},
	"hubspot": {
		Slug:    "hubspot",
		Title:   "HubSpot",
		Aliases: []string{"com.pulsemcp.mirror/hubspot"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.hubspot.com", Transport: "streamable-http", Tenanted: false},
		},
	},
	"intercom": {
		Slug:    "intercom",
		Title:   "Intercom",
		Aliases: []string{"com.pulsemcp.mirror/intercom"},
		Remotes: []generatedRemote{
			{ID: "us", URL: "https://mcp.intercom.com/mcp", Transport: "streamable-http", Tenanted: true},
			{ID: "eu", URL: "https://mcp.eu.intercom.com/mcp", Transport: "streamable-http", Tenanted: true},
		},
	},
	"salesforce": {
		Slug:    "salesforce",
		Title:   "Salesforce",
		Aliases: []string{"com.pulsemcp.mirror/gram-salesforce"},
		Remotes: []generatedRemote{
			{ID: "sobject-reads-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-reads", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-reads-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-reads", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-mutations-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-mutations", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-mutations-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-mutations", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-deletes-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-deletes", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-deletes-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-deletes", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-all-production", URL: "https://api.salesforce.com/platform/mcp/v1/platform/sobject-all", Transport: "streamable-http", Tenanted: false},
			{ID: "sobject-all-sandbox", URL: "https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-all", Transport: "streamable-http", Tenanted: false},
		},
	},
	"snowflake": {
		Slug:    "snowflake",
		Title:   "Snowflake",
		Aliases: []string{"com.pulsemcp.mirror/gram-snowflake"},
		Remotes: []generatedRemote{
			{ID: "cortex-agent-mcp", URL: "https://<account_url>/api/v2/databases/<mcp_database>/schemas/<mcp_schema>/mcp-servers/<mcp_server_name>", Transport: "streamable-http", Tenanted: true},
		},
	},
	"x": {
		Slug:    "x",
		Title:   "X",
		Aliases: []string{"com.pulsemcp.mirror/xdevplatform-xmcp"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://api.x.com/mcp", Transport: "streamable-http", Tenanted: false},
		},
	},
	"zapier": {
		Slug:    "zapier",
		Title:   "Zapier",
		Aliases: []string{"com.pulsemcp.mirror/zapier"},
		Remotes: []generatedRemote{
			{ID: "hosted", URL: "https://mcp.zapier.com/api/v1/connect", Transport: "streamable-http", Tenanted: false},
		},
	},
}

var generatedAliasToSlug = map[string]GuideSlug{
	"com.googleapis.compute/mcp":            "google-compute-engine",
	"com.pulsemcp.mirror/asana-mcp":         "asana",
	"com.pulsemcp.mirror/box":               "box",
	"com.pulsemcp.mirror/google-bigquery":   "google-big-query",
	"com.pulsemcp.mirror/gram-salesforce":   "salesforce",
	"com.pulsemcp.mirror/gram-snowflake":    "snowflake",
	"com.pulsemcp.mirror/hubspot":           "hubspot",
	"com.pulsemcp.mirror/intercom":          "intercom",
	"com.pulsemcp.mirror/xdevplatform-xmcp": "x",
	"com.pulsemcp.mirror/zapier":            "zapier",
	"io.github.github/github-mcp-server":    "github",
}

var generatedURLToRefs = map[string][]ServerRef{
	"https://<account_url>/api/v2/databases/<mcp_database>/schemas/<mcp_schema>/mcp-servers/<mcp_server_name>": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"https://api.githubcopilot.com/mcp": {
		{Guide: "github", Remote: "hosted"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-all": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-deletes": {
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-mutations": {
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/platform/sobject-reads": {
		{Guide: "salesforce", Remote: "sobject-reads-production"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-all": {
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-deletes": {
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-mutations": {
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
	},
	"https://api.salesforce.com/platform/mcp/v1/sandbox/platform/sobject-reads": {
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"https://api.x.com/mcp": {
		{Guide: "x", Remote: "hosted"},
	},
	"https://bigquery.googleapis.com/mcp": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"https://compute.googleapis.com/mcp": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"https://mcp.asana.com/v2/mcp": {
		{Guide: "asana", Remote: "hosted"},
	},
	"https://mcp.box.com": {
		{Guide: "box", Remote: "hosted"},
	},
	"https://mcp.eu.intercom.com/mcp": {
		{Guide: "intercom", Remote: "eu"},
	},
	"https://mcp.hubspot.com": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"https://mcp.intercom.com/mcp": {
		{Guide: "intercom", Remote: "us"},
	},
	"https://mcp.zapier.com/api/v1/connect": {
		{Guide: "zapier", Remote: "hosted"},
	},
}

var generatedProvenanceToRefs = map[string][]ServerRef{
	"API": {
		{Guide: "asana", Remote: "hosted"},
	},
	"About Box MCP Server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Account identifiers": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Activate MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Adding Integration Credentials for Customer-Instance Integrations": {
		{Guide: "box", Remote: "hosted"},
	},
	"Anthropic Messages API": {
		{Guide: "box", Remote: "hosted"},
	},
	"App management and integrations": {
		{Guide: "asana", Remote: "hosted"},
	},
	"App only authentication and OAuth 2.0 Bearer Token": {
		{Guide: "x", Remote: "hosted"},
	},
	"Approving OAuth apps for your organization": {
		{Guide: "github", Remote: "hosted"},
	},
	"Apps": {
		{Guide: "x", Remote: "hosted"},
	},
	"Asana": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Authenticate to Google and Google Cloud MCP servers": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Authenticating to the REST API": {
		{Guide: "github", Remote: "hosted"},
	},
	"Authentication": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
		{Guide: "x", Remote: "hosted"},
	},
	"Authorizing OAuth apps": {
		{Guide: "github", Remote: "hosted"},
	},
	"Available Tools": {
		{Guide: "box", Remote: "hosted"},
	},
	"BigQuery IAM roles and permissions": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP endpoint": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP endpoint (tools/list 200 unauthenticated; tools/call 401)": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP protected-resource metadata": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"BigQuery MCP reference": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Box MCP resource documentation": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box MCP server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box Model Context Protocol Server": {
		{Guide: "box", Remote: "hosted"},
	},
	"Box docs index": {
		{Guide: "box", Remote: "hosted"},
	},
	"CREATE MCP SERVER": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"CREATE ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"CREATE SECURITY INTEGRATION (Snowflake OAuth)": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Claude Code": {
		{Guide: "box", Remote: "hosted"},
	},
	"Compute Engine IAM roles and permissions": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP endpoint (tools/list 200 unauthenticated, tools/call 401)": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP protected-resource metadata": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Compute Engine MCP reference": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Configure Cursor": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Configure Postman": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Configure Snowflake OAuth for custom clients": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Configure a third-party application to connect to Snowflake": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Configure an email channel for OAuth with Gmail": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Configure the OAuth consent screen and choose scopes": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Configuring Box AI": {
		{Guide: "box", Remote: "hosted"},
	},
	"Configuring the GitHub MCP Server for GitHub Enterprise": {
		{Guide: "github", Remote: "hosted"},
	},
	"Connect Claude with Salesforce Hosted MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Connecting Coding Clients to Asana's V2 server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Connecting an MCP Client": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Cortex Agents access control and authentication": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Create an External Client App": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Create and manage Cortex Agents": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Create future reservation requests": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Creating an OAuth app": {
		{Guide: "github", Remote: "hosted"},
	},
	"Developer Console": {
		{Guide: "x", Remote: "hosted"},
	},
	"Developer updates for June 2026": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Enable and disable services": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Enterprise Settings: Content & Sharing Tab": {
		{Guide: "box", Remote: "hosted"},
	},
	"GRANT DATABASE ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"GRANT ROLE": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"GRANT privileges to role": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Get started with the Google Auth Platform": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Getting Access": {
		{Guide: "x", Remote: "hosted"},
	},
	"Getting Started with Managed Snowflake MCP Server": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"GitHub MCP Registry": {
		{Guide: "box", Remote: "hosted"},
	},
	"GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"GitHub MCP Server Installation Guides": {
		{Guide: "github", Remote: "hosted"},
	},
	"GitHub Remote MCP Integration Guide for MCP Host Authors": {
		{Guide: "github", Remote: "hosted"},
	},
	"Google Cloud MCP quotas and system limits": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Google Cloud MCP servers overview": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Google Cloud MCP servers release notes": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Google authorization-server metadata": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Grant an IAM role by using the Google Cloud console": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"HubSpot MCP Server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"HubSpot developer documentation index": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"HubSpot user permissions guide": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Integrate AI tools with the HubSpot MCP server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Integrating with Asana's MCP Server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Intercom developer documentation index": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Intercom sign-in page": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Log In to Your Org": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"MCP Frequently Asked Questions": {
		{Guide: "box", Remote: "hosted"},
	},
	"MCP Server Activity Report": {
		{Guide: "box", Remote: "hosted"},
	},
	"MCP servers for the X API and X developer docs": {
		{Guide: "x", Remote: "hosted"},
	},
	"Make your first Google Health API call": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Manage App Audience": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Manage App Data Access": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Manage OAuth App Branding": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Manage Tool Access": {
		{Guide: "box", Remote: "hosted"},
	},
	"Manage your app": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Managing Box MCP Servers": {
		{Guide: "box", Remote: "hosted"},
	},
	"Model Context Protocol (MCP)": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"OAuth": {
		{Guide: "asana", Remote: "hosted"},
	},
	"OAuth 2.0 Authorization Code Flow with PKCE": {
		{Guide: "x", Remote: "hosted"},
	},
	"OAuth 2.0 Scopes for Google APIs": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"OAuth Scopes": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Policies & Governance for the GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Prerequisite 1 - Create and Configure an External Client App": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Pricing": {
		{Guide: "box", Remote: "hosted"},
	},
	"Products Supporting MCP": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Public Beta: Self-Service MCP Auth Apps for the HubSpot Remote MCP Server": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Querying semi-structured data": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Quotas and system limits": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Regional Data Hosting": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Remote GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Remote HubSpot MCP server is now generally available": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Requesting organization approval for OAuth apps": {
		{Guide: "github", Remote: "hosted"},
	},
	"Revoke access to a Google Cloud project": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"SObject All": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Deletes": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Mutations": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SObject Reads": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"SYSTEM$SHOW_OAUTH_CLIENT_SECRETS": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Salesforce Hosted MCP Servers": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce Hosted MCP Servers Are Now Generally Available": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce SObject Reads production endpoint": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Salesforce SObject Reads protected-resource metadata": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Scope Filtering": {
		{Guide: "github", Remote: "hosted"},
	},
	"Sensitive scope verification": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Server Connection Failures": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Set up a Workspace": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Set up authentication for Google and Google Cloud MCP servers": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Set up authentication to Google and Google Cloud MCP servers": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Setting up OAuth": {
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
	},
	"Setting up the GitHub MCP Server": {
		{Guide: "github", Remote: "hosted"},
	},
	"Share your app": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Snowflake Cortex documentation index": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake Documentation index": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake OAuth overview": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Snowflake-managed MCP server": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Speakeasy identity-provider attachment sheet": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Speakeasy identity-provider form fields": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Speakeasy setup canonical section": {
		{Guide: "asana", Remote: "hosted"},
		{Guide: "github", Remote: "hosted"},
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "hubspot", Remote: "hosted"},
		{Guide: "intercom", Remote: "eu"},
		{Guide: "intercom", Remote: "us"},
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
		{Guide: "x", Remote: "hosted"},
	},
	"Spring 2026 Spotlight": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"Standard MCP Servers Reference": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Submitting your app for verification": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Supported AI Platforms": {
		{Guide: "box", Remote: "hosted"},
	},
	"Supported products": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Try BigQuery using the sandbox": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Understanding AI Units In Box": {
		{Guide: "box", Remote: "hosted"},
	},
	"Understanding Requests to Authorize or Allow Applications": {
		{Guide: "box", Remote: "hosted"},
	},
	"Update Salesforce Settings for Tableau Next Embedding": {
		{Guide: "salesforce", Remote: "sobject-all-production"},
		{Guide: "salesforce", Remote: "sobject-all-sandbox"},
		{Guide: "salesforce", Remote: "sobject-deletes-production"},
		{Guide: "salesforce", Remote: "sobject-deletes-sandbox"},
		{Guide: "salesforce", Remote: "sobject-mutations-production"},
		{Guide: "salesforce", Remote: "sobject-mutations-sandbox"},
		{Guide: "salesforce", Remote: "sobject-reads-production"},
		{Guide: "salesforce", Remote: "sobject-reads-sandbox"},
	},
	"Use the BigQuery MCP server": {
		{Guide: "google-big-query", Remote: "hosted"},
	},
	"Use the Compute Engine MCP server": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"Using Asana's MCP Server": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Using OAuth 2.0 to Access Google APIs": {
		{Guide: "google-big-query", Remote: "hosted"},
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"V2 MCP server now generally available": {
		{Guide: "asana", Remote: "hosted"},
	},
	"What is the admin console?": {
		{Guide: "asana", Remote: "hosted"},
	},
	"Working with workspaces": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"Workspaces": {
		{Guide: "snowflake", Remote: "cortex-agent-mcp"},
	},
	"X API pay-per-usage pricing and credits": {
		{Guide: "x", Remote: "hosted"},
	},
	"X Developer Platform documentation index": {
		{Guide: "x", Remote: "hosted"},
	},
	"com.googleapis.compute/mcp": {
		{Guide: "google-compute-engine", Remote: "hosted"},
	},
	"com.pulsemcp.mirror/box": {
		{Guide: "box", Remote: "hosted"},
	},
	"com.pulsemcp.mirror/hubspot": {
		{Guide: "hubspot", Remote: "hosted"},
	},
	"com.pulsemcp.mirror/zapier": {
		{Guide: "zapier", Remote: "hosted"},
	},
	"xurl": {
		{Guide: "x", Remote: "hosted"},
	},
}
